#!/bin/bash
set -e

# Validate argument thresholds
if [ "$#" -ne 3 ]; then
    echo "========================================================================="
    echo " Heimdal ASN.1 Compliance Test Gate"
    echo "========================================================================="
    echo "Usage: docker run --rm -v \$(pwd):/workspace <image_name> <schema.asn> <TopLevelType> <test_vector.der>"
    echo ""
    echo "Example: docker run --rm -v \$(pwd):/workspace asn1-gate rfc9935.asn MLSecureMessage test.der"
    echo "========================================================================="
    exit 1
fi

SCHEMA_FILE=$1
TOP_TYPE=$2
DER_FILE=$3
PREFIX="compiled_schema"

# 1. Compile the official ASN.1 Schema using Heimdal's advanced parser
echo "==> [Step 1/4] Parsing & compiling schema: ${SCHEMA_FILE}..."
asn1_compile "${SCHEMA_FILE}" "${PREFIX}"

# 2. Dynamically generate the strict C test harness matching the specified target type
echo "==> [Step 2/4] Injecting type context into C validation harness..."
cat << EOF > verify_der.c
#include <stdio.h>
#include <stdlib.h>
#include "asn1_${PREFIX}.h"

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Error: Missing target binary DER file path.\\n");
        return 2;
    }

    FILE *f = fopen(argv[1], "rb");
    if (!f) {
        fprintf(stderr, "Error: Unable to open DER file %s\\n", argv[1]);
        return 2;
    }
    
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);

    unsigned char *buffer = malloc(fsize);
    if (!buffer) {
        fprintf(stderr, "Error: Out of memory buffer allocation.\\n");
        fclose(f);
        return 2;
    }
    
    size_t read_bytes = fread(buffer, 1, fsize, f);
    fclose(f);

    // Call the specific decoder function generated by Heimdal for your type
    ${TOP_TYPE} message;
    size_t decoded_size = 0;
    
    int result = decode_${TOP_TYPE}(buffer, fsize, &message, &decoded_size);
    free(buffer);
    
    if (result == 0) {
        printf(" SUCCESS: Python wire bytes strictly align with the formal ASN.1 layout.\\n");
        free_${TOP_TYPE}(&message);
        return 0; // Test Passes!
    } else {
        fprintf(stderr, " FAILURE: Structural mismatch or constraint violation detected.\\n");
        fprintf(stderr, "          Heimdal Error Code: %d\\n", result);
        return 1; // Test Fails!
    }
}
EOF

# 3. Compile the system binaries pulling configuration directly from krb5-config
echo "==> [Step 3/4] Fetching Heimdal linkage maps and building validator..."
HEIMDAL_CFLAGS=$(krb5-config.heimdal --cflags asn1)
HEIMDAL_LIBS=$(krb5-config.heimdal --libs asn1)

gcc -I. ${HEIMDAL_CFLAGS} verify_der.c "asn1_${PREFIX}.c" ${HEIMDAL_LIBS} -o der_validator

# 4. Perform strict wire verification
echo "==> [Step 4/4] Executing byte-verification check on: ${DER_FILE}..."
./der_validator "${DER_FILE}"
